---
title: "Variables"
author: "Binghan Shen"
date: "2023-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```

```{r}
# Load datasets
b01002_df <- read.csv("data/B01002.csv")
b05002_df <- read.csv("data/B05002.csv")
b11012_df <- read.csv("data/B11012.csv")
b14001_df <- read.csv("data/B14001.csv")
b17020_df <- read.csv("data/B17020.csv")
b19122_df <- read.csv("data/B19122.csv")
b21001_df <- read.csv("data/B21001.csv")
b22001_df <- read.csv("data/B22001.csv")
b23025_df <- read.csv("data/B23025.csv")
b28010_df <- read.csv("data/B28010.csv")

## median_age
median_age_df <- arrange(b01002_df[b01002_df$variable == 'B01002_001',], GEOID)
median_age <- median_age_df$estimate

## proportion_foreign_born: b05002_df
numerator_2 <- arrange(b05002_df[b05002_df$label == 'Estimate!!Total:!!Foreign born:',], GEOID)
denominator_2 <- arrange(b05002_df[b05002_df$label == 'Estimate!!Total:',], GEOID)
proportion_foreign_born <- numerator_2$estimate / denominator_2$estimate

## proportion_married_couple_families: b11012_df
numerator_3 <- arrange(b11012_df[b11012_df$label == 'Estimate!!Total:!!Married-couple household:',], GEOID)
denominator_3 <- arrange(b11012_df[b11012_df$label == 'Estimate!!Total:',], GEOID)
proportion_married_couple_families <- numerator_3$estimate / denominator_3$estimate

## proportion_school_enrolled: b14001_df
numerator_4 <- arrange(b14001_df[b14001_df$label == 'Estimate!!Total:!!Enrolled in school:',], GEOID)
denominator_4 <- arrange(b14001_df[b14001_df$label == 'Estimate!!Total:',], GEOID)
proportion_school_enrolled <- numerator_4$estimate / denominator_4$estimate

## proportion_poverty: b17020_df
numerator_5 <- arrange(b17020_df[b17020_df$label == 'Estimate!!Total:!!Income in the past 12 months below poverty level:' & b17020_df$concept == 'POVERTY STATUS IN THE PAST 12 MONTHS BY AGE',], GEOID)
denominator_5 <- arrange(b17020_df[b17020_df$label == 'Estimate!!Total:' & b17020_df$concept == 'POVERTY STATUS IN THE PAST 12 MONTHS BY AGE',], GEOID)
proportion_poverty <- numerator_5$estimate / denominator_5$estimate

# Proportion of No Earners
numerator_6 <- arrange(b19122_df[b19122_df$label == 'Estimate!!Total:!!No workers in past 12 months:',], GEOID)
denominator_6 <- arrange(b19122_df[b19122_df$label == 'Estimate!!Total:',], GEOID)
proportion_no_earners <- numerator_6$estimate / denominator_6$estimate

# Proportion of Veterans
numerator_7 <- arrange(b21001_df[b21001_df$label == 'Estimate!!Total:!!Civilian veterans:',], GEOID)
denominator_7 <- arrange(b21001_df[b21001_df$label == 'Estimate!!Total:',], GEOID)
proportion_veteran <- numerator_7$estimate / denominator_7$estimate

# Proportion who Received Food Stamps/SNAP
numerator_8 <- arrange(b22001_df[b22001_df$label == 'Estimate!!Total:!!Household did not receive Food Stamps/SNAP in the past 12 months:',], GEOID)
denominator_8 <- arrange(b22001_df[b22001_df$label == 'Estimate!!Total:',], GEOID)
proportion_received_food_stamps <- numerator_8$estimate / denominator_8$estimate

# Proportion Not in Labor Force
numerator_9 <- arrange(b23025_df[b23025_df$label == 'Estimate!!Total:!!Not in labor force:',], GEOID)
denominator_9 <- arrange(b23025_df[b23025_df$label == 'Estimate!!Total:',], GEOID)
proportion_not_in_labor_force <- numerator_9$estimate / denominator_9$estimate

# Proportion with Computing Devices
numerator_10 <- arrange(b28010_df[b28010_df$label == 'Estimate!!Total:!!Has one or more types of computing devices:',], GEOID)
denominator_10 <- arrange(b28010_df[b28010_df$label == 'Estimate!!Total:',], GEOID)
proportion_with_computing_devices <- numerator_10$estimate / denominator_10$estimate

```
