---
title: "Final Project_Group 3"
author: "Binghan Shen, Yifan Lu, Yucheng Liu"
output: html_document
date: "2023-11-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("tidycensus")
library(tidycensus)
library(tidyverse)
library(dplyr)
# install.packages("reader")
library(reader)
# install.packages("purrr")
library(purrr)
```

```{r}
# API key for tidycensus
census_api_key("879c99305c92c44bc76fa12b239039001ae1a69d", overwrite = TRUE, install = TRUE)
```

```{r}
# Load available variables for ACS 5-year 2021
variables <- load_variables(year = 2021, dataset = "acs5", cache = TRUE)

# Specific table codes
specific_tables <- c("B01002", "B05002", "B14001", "B11012", "B17020", "B19122", "B21001", "B22001", "B23025", "B28010")

# Loop to download and save data for each specified table
for (table_code in specific_tables) {
    # Filter variables for the current table, including label and concept
    current_table_variables <- subset(variables, grepl(paste0("^", table_code), variables$name), 
                                      select = c("name", "label", "concept"))

    # Download data for the current table
    acs_data <- get_acs(geography = "state", 
                        variables = current_table_variables$name, 
                        year = 2021, 
                        survey = "acs5")

    # Merge the data with labels and concepts for clarity
    acs_data_labeled <- merge(acs_data, current_table_variables, by.x = "variable", by.y = "name")

    # Save the merged data to CSV in the 'data' folder
    write.csv(acs_data_labeled, file.path("data", paste0(table_code, ".csv")), row.names = FALSE)
    }
```

```{r}
# Load datasets
b01002_df <- read.csv("data/B01002.csv")
b05002_df <- read.csv("data/B05002.csv")
b11012_df <- read.csv("data/B11012.csv")
b14001_df <- read.csv("data/B14001.csv")
b17020_df <- read.csv("data/B17020.csv")
b19122_df <- read.csv("data/B19122.csv")
b21001_df <- read.csv("data/B21001.csv")
b22001_df <- read.csv("data/B22001.csv")
b23025_df <- read.csv("data/B23025.csv")
b28010_df <- read.csv("data/B28010.csv")

## median_age
median_age_df <- arrange(b01002_df[b01002_df$variable == 'B01002_001',], GEOID)
median_age <- median_age_df$estimate

## proportion_foreign_born: b05002_df
numerator_2 <- arrange(b05002_df[b05002_df$label == 'Estimate!!Total:!!Foreign born:',], GEOID)
denominator_2 <- arrange(b05002_df[b05002_df$label == 'Estimate!!Total:',], GEOID)
proportion_foreign_born <- numerator_2$estimate / denominator_2$estimate

## proportion_married_couple_families: b11012_df
numerator_3 <- arrange(b11012_df[b11012_df$label == 'Estimate!!Total:!!Married-couple household:',], GEOID)
denominator_3 <- arrange(b11012_df[b11012_df$label == 'Estimate!!Total:',], GEOID)
proportion_married_couple_families <- numerator_3$estimate / denominator_3$estimate

## proportion_school_enrolled: b14001_df
numerator_4 <- arrange(b14001_df[b14001_df$label == 'Estimate!!Total:!!Enrolled in school:',], GEOID)
denominator_4 <- arrange(b14001_df[b14001_df$label == 'Estimate!!Total:',], GEOID)
proportion_school_enrolled <- numerator_4$estimate / denominator_4$estimate

## proportion_poverty: b17020_df
numerator_5 <- arrange(b17020_df[b17020_df$label == 'Estimate!!Total:!!Income in the past 12 months below poverty level:' & b17020_df$concept == 'POVERTY STATUS IN THE PAST 12 MONTHS BY AGE',], GEOID)
denominator_5 <- arrange(b17020_df[b17020_df$label == 'Estimate!!Total:' & b17020_df$concept == 'POVERTY STATUS IN THE PAST 12 MONTHS BY AGE',], GEOID)
proportion_poverty <- numerator_5$estimate / denominator_5$estimate

# Proportion of No Earners
numerator_6 <- arrange(b19122_df[b19122_df$label == 'Estimate!!Total:!!No workers in past 12 months:',], GEOID)
denominator_6 <- arrange(b19122_df[b19122_df$label == 'Estimate!!Total:',], GEOID)
proportion_no_earners <- numerator_6$estimate / denominator_6$estimate

# Proportion of Veterans
numerator_7 <- arrange(b21001_df[b21001_df$label == 'Estimate!!Total:!!Civilian veterans:',], GEOID)
denominator_7 <- arrange(b21001_df[b21001_df$label == 'Estimate!!Total:',], GEOID)
proportion_veteran <- numerator_7$estimate / denominator_7$estimate

# Proportion who Received Food Stamps/SNAP
numerator_8 <- arrange(b22001_df[b22001_df$label == 'Estimate!!Total:!!Household did not receive Food Stamps/SNAP in the past 12 months:',], GEOID)
denominator_8 <- arrange(b22001_df[b22001_df$label == 'Estimate!!Total:',], GEOID)
proportion_received_food_stamps <- numerator_8$estimate / denominator_8$estimate

# Proportion Not in Labor Force
numerator_9 <- arrange(b23025_df[b23025_df$label == 'Estimate!!Total:!!Not in labor force:',], GEOID)
denominator_9 <- arrange(b23025_df[b23025_df$label == 'Estimate!!Total:',], GEOID)
proportion_not_in_labor_force <- numerator_9$estimate / denominator_9$estimate

# Proportion with Computing Devices
numerator_10 <- arrange(b28010_df[b28010_df$label == 'Estimate!!Total:!!Has one or more types of computing devices:',], GEOID)
denominator_10 <- arrange(b28010_df[b28010_df$label == 'Estimate!!Total:',], GEOID)
proportion_with_computing_devices <- numerator_10$estimate / denominator_10$estimate
```

```{r}
# Load datasets
b01002_df <- read.csv("data/B01002.csv")
b05002_df <- read.csv("data/B05002.csv")
b11012_df <- read.csv("data/B11012.csv")
b14001_df <- read.csv("data/B14001.csv")
b17020_df <- read.csv("data/B17020.csv")
b19122_df <- read.csv("data/B19122.csv")
b21001_df <- read.csv("data/B21001.csv")
b22001_df <- read.csv("data/B22001.csv")
b23025_df <- read.csv("data/B23025.csv")
b28010_df <- read.csv("data/B28010.csv")

# Extract and compute necessary variables
median_age <- b01002_df %>% filter(variable == 'B01002_001') %>% select(GEOID, estimate)
proportion_foreign_born <- b05002_df %>% filter(label == 'Estimate!!Total:!!Foreign born:') %>% select(GEOID, estimate)
proportion_married_couple_families <- b11012_df %>% filter(label == 'Estimate!!Total:!!Married-couple household:') %>% select(GEOID, estimate)
proportion_school_enrolled <- b14001_df %>% filter(label == 'Estimate!!Total:!!Enrolled in school:') %>% select(GEOID, estimate)
proportion_poverty <- b17020_df %>% filter(label == 'Estimate!!Total:!!Income in the past 12 months below poverty level:' & concept == 'POVERTY STATUS IN THE PAST 12 MONTHS BY AGE') %>% select(GEOID, estimate)
proportion_no_earners <- b19122_df %>% filter(label == 'Estimate!!Total:!!No workers in past 12 months:') %>% select(GEOID, estimate)
proportion_veteran <- b21001_df %>% filter(label == 'Estimate!!Total:!!Civilian veterans:') %>% select(GEOID, estimate)
proportion_received_food_stamps <- b22001_df %>% filter(label == 'Estimate!!Total:!!Household did not receive Food Stamps/SNAP in the past 12 months:') %>% select(GEOID, estimate)
proportion_not_in_labor_force <- b23025_df %>% filter(label == 'Estimate!!Total:!!Not in labor force:') %>% select(GEOID, estimate)
proportion_with_computing_devices <- b28010_df %>% filter(label == 'Estimate!!Total:!!Has one or more types of computing devices:') %>% select(GEOID, estimate)

# Join the datasets together by GEOID
combined_data <- reduce(list(median_age, proportion_foreign_born, proportion_married_couple_families, proportion_school_enrolled, proportion_poverty, proportion_no_earners, proportion_veteran, proportion_received_food_stamps, proportion_not_in_labor_force, proportion_with_computing_devices), full_join, by = "GEOID")

# Check the combined data frame
head(combined_data)
```
